version: '3.8'

services:
  kali:
    build:
      context: .
      dockerfile: docker/Dockerfile  # Correct path to Dockerfile
    container_name: kali-linux-container
    ports:
      - "2222:22"  # SSH access
      - "80:80"    # HTTP access
    volumes:
      - ./data:/home/kaliuser/data
    stdin_open: true
    tty: true
