name: build-docker-images

on:
  push:
    branches:
      - main
      - development

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        platform: [amd64] # multi-architecture [amd64, arm64]

    outputs:
      platforms: ${{ matrix.platform }}
      git_sha: ${{ steps.git_sha.outputs.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Git commit SHA
        id: git_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image (kali)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          output: type=docker
          push: false
          tags: capstone-kali:${{ steps.git_sha.outputs.sha }}-${{ matrix.platform }}
