name: notify-pipeline-status
on:
  workflow_call:
    inputs:
      pipeline:
        required: true
        type: string
      status_on_success_push:
        required: true
        type: string
      status_on_success_update_chart:
        required: true
        type: string
      error_message_push:
        required: true
        type: string
      error_output_push:
        required: true
        type: string
      error_message_update_chart:
        required: true
        type: string
      error_output_update_chart:
        required: true
        type: string

  workflow_run:
    workflows: ["publish-docker-images"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Discord notification on success
        if: ${{ inputs.status_on_success_push == 'success' && inputs.status_on_success_update_chart == 'success' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "**[ STATUS MESSAGE ] The project ${{ inputs.pipeline }} successfully built and published! \n\n Project Image Repository URL: ${{ vars.PROJECT_IMAGE_REPOSITORY_URL }} \n Project Repository URL: ${{ vars.PROJECT_REPOSITORY_URL }} \n Project Chart URL: ${{ vars.PROJECT_CHART_URL }}**"

      - name: Send Discord notification on failure
        if: ${{ inputs.status_on_success_push == 'failure' || inputs.status_on_success_update_chart == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "**[ ERROR ] The project ${{ inputs.pipeline }} failed to build and publish:\n\n**Push Error:**\n${{ inputs.error_message_push }}\n${{ inputs.error_output_push }}\n\n**Update Chart Error:**\n${{ inputs.error_message_update_chart }}\n${{ inputs.error_output_update_chart }}"

