name: notify-pipeline-status

on:
  workflow_call:
    inputs:
      pipeline:
        required: true
        type: string
      status_on_success_push:
        required: true
        type: string
      status_on_success_update_chart:
        required: true
        type: string
      error_message_push:
        required: true
        type: string
      error_output_push:
        required: true
        type: string
      error_message_update_chart:
        required: true
        type: string
      error_output_update_chart:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Discord notification on success
        if: ${{ inputs.status_on_success_push == 'success' && inputs.status_on_success_update_chart == 'success' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {
              "content": "**[ STATUS MESSAGE ] The project ${{ inputs.pipeline }} successfully built and published!**",
              "embeds": [
                {
                  "title": "Project Repository URL",
                  "url": "https://github.com/elysiansky/capstone-kali",
                  "description": "https://github.com/elysiansky/capstone-kali",
                  "image": {
                    "url": "https://link-to-image-for-project-repository-url"
                  }
                },
                {
                  "title": "Project Chart URL",
                  "url": "https://github.com/elysiansky/capstone-chart-kali",
                  "description": "https://github.com/elysiansky/capstone-chart-kali",
                  "image": {
                    "url": "https://link-to-image-for-project-chart-url"
                  }
                }
              ]
            }

      - name: Send Discord notification on failure
        if: ${{ inputs.status_on_success_push == 'failure' || inputs.status_on_success_update_chart == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {
              "content": "**[ ERROR ] The project ${{ inputs.pipeline }} failed to build and publish:**",
              "embeds": [
                {
                  "title": "Push Error",
                  "description": "${{ inputs.error_message_push }}\n${{ inputs.error_output_push }}"
                },
                {
                  "title": "Update Chart Error",
                  "description": "${{ inputs.error_message_update_chart }}\n${{ inputs.error_output_update_chart }}"
                }
              ]
            }
