name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify DockerHub Secrets
        run: echo "DockerHub Secrets Verified"

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Publish Docker Image (Kali)
        id: publish_kali
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/kali-linux:${{ github.sha }}-${{ github.event.inputs.platforms }}
          push: true

      - name: Post Publish Docker Image (Kali)
        run: echo "Docker Image Published"

      - name: Notify
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Build succeeded for platforms: ${{ github.event.inputs.platforms }} with Git SHA: ${{ github.sha }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Build failed for platforms: ${{ github.event.inputs.platforms }} with Git SHA: ${{ github.sha }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
