name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify DockerHub Secrets
        run: echo "DockerHub Secrets Verified"

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Tag
        id: vars
        run: |
          echo "TAG=${{ secrets.DOCKER_USERNAME }}/kali-linux:${{ github.sha }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Publish Docker Image (Kali)
        id: publish_kali
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          tags: ${{ env.TAG }}
          push: true

      - name: Notify on Success
        if: success()
        uses: actions/github-script@v3
        with:
          script: |
            const pipeline = 'capstone-kali';
            const status_on_success_push = 'success';
            const status_on_success_update_chart = 'success';
            const error_message_push = '';
            const error_output_push = '';
            const error_message_update_chart = '';
            const error_output_update_chart = '';
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'notify.yaml',
              ref: context.ref,
              inputs: {
                pipeline: pipeline,
                status_on_success_push: status_on_success_push,
                status_on_success_update_chart: status_on_success_update_chart,
                error_message_push: error_message_push,
                error_output_push: error_output_push,
                error_message_update_chart: error_message_update_chart,
                error_output_update_chart: error_output_update_chart,
              }
            });

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            const pipeline = 'capstone-kali';
            const status_on_success_push = 'failure';
            const status_on_success_update_chart = 'failure';
            const error_message_push = 'Publish Docker Image Failed';
            const error_output_push = `Error output: ${steps.publish_kali.outcome}`;
            const error_message_update_chart = '';
            const error_output_update_chart = '';
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'notify.yaml',
              ref: context.ref,
              inputs: {
                pipeline: pipeline,
                status_on_success_push: status_on_success_push,
                status_on_success_update_chart: status_on_success_update_chart,
                error_message_push: error_message_push,
                error_output_push: error_output_push,
                error_message_update_chart: error_message_update_chart,
                error_output_update_chart: error_output_update_chart,
              }
            });
