name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify DockerHub Secrets
        run: echo "DockerHub Secrets Verified"

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Publish Docker Image (Kali)
        id: publish_kali
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/kali-linux:${{ github.sha }}-${{ github.event.inputs.platforms }}
          push: true

      - name: Post Publish Docker Image (Kali)
        run: echo "Docker Image Published"

      - name: Notify on Success
        if: success()
        uses: ./.github/workflows/notify.yaml
        with:
          pipeline: "capstone-kali"
          status_on_success_push: ${{ steps.publish_kali.outcome }}
          status_on_success_update_chart: "success"
          error_message_push: ""
          error_output_push: ""
          error_message_update_chart: ""
          error_output_update_chart: ""
        secrets:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify on Failure
        if: failure()
        uses: ./.github/workflows/notify.yaml
        with:
          pipeline: "capstone-kali"
          status_on_success_push: "failure"
          status_on_success_update_chart: "failure"
          error_message_push: "Docker Image Publish Failed"
          error_output_push: ${{ steps.publish_kali.outcome }}
          error_message_update_chart: "Update Chart Failed"
          error_output_update_chart: "No updates to chart"
        secrets:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
