name: Publish Docker Images

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types: [completed]
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms'
        required: true
        default: 'linux/amd64'
      git_sha:
        description: 'Git SHA'
        required: true
        default: 'latest'

jobs:
  on-success-push:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Debug Outputs
        run: |
          echo "Platforms: ${{ github.event.inputs.platforms }}"
          echo "Git SHA: ${{ github.event.inputs.git_sha }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify DockerHub Secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image (Kali)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ github.event.inputs.platforms }}
          tags: ${{ secrets.DOCKER_USERNAME }}/kali-linux:${{ github.event.inputs.git_sha }}-${{ github.event.inputs.platforms }}
          push: true

  on-success-update-chart:
    runs-on: ubuntu-latest
    environment: development
    needs: on-success-push
    steps:
      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v2
        with:
          repository: elysiansky/capstone-chart-kali
          ref: main
          token: ${{ secrets.HELM_CHART_PERSONAL_ACCESS_TOKEN }}

      - name: Debug values.yaml Before Update
        run: cat values.yaml

      - name: Update Helm Chart Values Image Tag
        run: |
          sed -i "s/tag:.*/tag: ${{ github.event.inputs.git_sha }}-${{ github.event.inputs.platforms }}/" values.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add values.yaml
          git status
          if ! git diff --cached --quiet; then
            git commit -m "Update image tag with latest Git SHA"
            git push
          else
            echo "No changes to commit"
          fi

  on-success-notify-discord:
    needs: on-success-update-chart
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug DISCORD_WEBHOOK Secret
        run: |
          echo "DISCORD_WEBHOOK: "
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "DISCORD_WEBHOOK is not set"
            exit 1
          else
            echo "DISCORD_WEBHOOK is set"
          fi

      - name: Send Notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Build succeeded for platforms: ${{ github.event.inputs.platforms }} with Git SHA: ${{ github.event.inputs.git_sha }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

