name: Publish Docker Images

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types: [completed]
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms'
        required: true
        default: 'linux/amd64'
      git_sha:
        description: 'Git SHA'
        required: true
        default: 'latest'

jobs:
  on-success-push:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Debug Outputs
        run: |
          echo "Platforms: ${{ github.event.inputs.platforms }}"
          echo "Git SHA: ${{ github.event.inputs.git_sha }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify DockerHub Secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image (Kali)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/kali-linux:${{ github.event.inputs.git_sha }}-linux-amd64
          push: true

  on-success-update-chart:
    runs-on: ubuntu-latest
    environment: development
    needs: on-success-push
    steps:
      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v2
        with:
          repository: elysiansky/capstone-chart-kali
          ref: main
          token: ${{ secrets.HELM_CHART_PERSONAL_ACCESS_TOKEN }}

      - name: Debug values.yaml Before Update
        run: cat values.yaml

      - name: Update Helm Chart Values Image Tag
        run: |
          sed -i "s/\(tag: \).*/\1${{ github.event.inputs.git_sha }}-linux-amd64/" values.yaml
          echo "After sed command:"
          cat values.yaml

      - name: Configure Git User Email
        run: git config --global user.email "action@github.com"

      - name: Configure Git User Name
        run: git config --global user.name "GitHub Action"

      - name: Add Changes
        run: git add values.yaml

      - name: Check Git Status
        run: git status

      - name: Commit Changes
        run: |
          git diff --cached --quiet || git commit -m "Update image tag with latest Git SHA"

      - name: Push Changes
        run: git push

      - name: No Changes to Commit
        if: failure()
        run: echo "No changes to commit"
