name: Publish Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify DockerHub Secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is not set"
            exit 1
          fi

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Tag
        id: set_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M')"

      - name: Publish Docker Image (Kali)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kali-linux:${{ steps.set_tag.outputs.tag }}

      - name: Verify Discord Webhook Secret
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "DISCORD_WEBHOOK is not set"
            exit 1
          fi

      - name: Notify on Success
        if: ${{ success() }}
        run: |
          echo "Sending success notification to Discord"
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Build succeeded for platforms with Git SHA: ${{ github.sha }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify on Failure
        if: ${{ failure() }}
        run: |
          echo "Sending failure notification to Discord"
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Build failed for platforms with Git SHA: ${{ github.sha }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
